# -*- encoding: utf-8; -*-
###
### Common user settings
###
users:
  FNJ:
  - name: "ふー"
    id: "foo"
    pw: "foo's password"
  - name: "ばー"
    id: "bar"
    pw: "bar's password"

  Rakuten:
    - name: "ふー"
      id: "foo"
      pw: "foo's password"
    - name: "ばー"
      id: "bar"
      pw: "bar's password"
    - name: "ばず"
      id: "baz"
      pw: "baz's password"

  Infoseek:
  - name: "ばー"
    id: "bar"
    pw: "bar's password"

  JPBank:
  - name: "ふー"
    id: "foo"
    pw: "foo's password"
    hint:
      "hint1_question?": "hint1_answer"
      "hint2_question?": "hint2_answer"
      "hint3_question?": "hint3_answer"

services:
  Rkeiba:
  - "ふー"
  RWebSearch:
  - "ふー"
  - "ばず"
  JPJrNISA:
  - "ふー"
